// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DBFirst.Entities;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DBFirst
{
    public partial interface IAppDbContextProcedures
    {
        Task<List<usp_getproductResult>> usp_getproductAsync(int? Product, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
